# Generated by Django 5.2.8 on 2025-11-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayectoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título (Puesto/Carrera)')),
                ('lugar', models.CharField(max_length=100, verbose_name='Lugar (Empresa/Institución)')),
                ('fecha', models.CharField(max_length=50, verbose_name='Fecha (Ej: 2023 - Presente)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción breve')),
            ],
            options={
                'verbose_name': 'Hito de Trayectoria',
                'verbose_name_plural': 'Trayectoria',
                'ordering': ['-id'],
            },
        ),
    ]
