# Generated by Django 5.2.8 on 2025-11-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trayectoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nombre del Certificado')),
                ('entidad', models.CharField(max_length=100, verbose_name='Institución (Ej: INACAP)')),
                ('fecha', models.CharField(max_length=50, verbose_name='Fecha de obtención')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='certificados/', verbose_name='Imagen/Diploma')),
                ('link_credencial', models.URLField(blank=True, null=True, verbose_name='Link de Validación')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
