# Generated by Django 5.2.8 on 2025-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='tipo',
            field=models.CharField(choices=[('BACK', 'Backend'), ('FRONT', 'Frontend'), ('OTHER', 'Herramientas / Otra')], default='OTHER', max_length=5, verbose_name='Tipo de Habilidad'),
        ),
    ]
