# Generated by Django 5.2.8 on 2025-12-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_habilidad_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={},
        ),
        migrations.AlterField(
            model_name='certificado',
            name='entidad',
            field=models.CharField(max_length=100, verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha',
            field=models.CharField(max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='red',
            field=models.CharField(max_length=50, verbose_name='Red Social'),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='tipo',
            field=models.CharField(choices=[('BACK', 'Backend'), ('FRONT', 'Frontend'), ('OTHER', 'Herramientas / Otros')], default='OTHER', max_length=5, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trayectoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='trayectoria',
            name='fecha',
            field=models.CharField(max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='trayectoria',
            name='lugar',
            field=models.CharField(max_length=100, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='trayectoria',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
